

from selenium import webdriver
from selenium.webdriver.common.by import By
from Test_data import data
import pytest
import time
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import ElementNotInteractableException


class Test_Sahana:
    url = "https://opensource-demo.orangehrmlive.com"


    @pytest.fixture
    def booting_function(self):
        self.driver = webdriver.Chrome()
        yield
        self.driver.close()

    def test_dropdown_admin(self,booting_function):
        self.driver.get(self.url)
        time.sleep(5)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.input_username).send_keys(data.Sahana_Data.username)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.input_password).send_keys(data.Sahana_Data.password)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.login_xpath).click()
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.admin_xpath).click()
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.user_management_xpath).click()
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.user_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.user_edit_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.user_dropdown_xpath).click()
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.user_dropdown_xpath).click()
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.status_xpath).click()
        print("Admin, CSS drop-down is displayed & Enabled, disabled drop-down is displayed")

    def test_new_employee_pim(self,booting_function):
        self.driver.get(self.url)
        time.sleep(5)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.input_username).send_keys(data.Sahana_Data.username)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.input_password).send_keys(data.Sahana_Data.password)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.login_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.pim_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.add_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.input_firstname).send_keys(data.Sahana_Data.firstname)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.input_lastname).send_keys(data.Sahana_Data.lastname)
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.toggle_xpath).click()
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.name_xpath).send_keys(data.Sahana_Data.name)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.enabled_xpath).click()
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.pass_xpath).send_keys(data.Sahana_Data.passw)
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.confirm_xpath).send_keys(data.Sahana_Data.passw)
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.save_xpath).click()
        print("Success")
    


    def test_validate_tabs(self,booting_function):
        self.driver.get(self.url)
        time.sleep(5)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.input_username).send_keys(data.Sahana_Data.username)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.input_password).send_keys(data.Sahana_Data.password)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.login_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.pim_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.user_edit_xpath).click()
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.personal_xpath).click()
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.contact_xpath).click()
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.emergency_xpath).click()
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.dependants_xpath).click()
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.immigration_xpath).click()
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.job_xpath).click()
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.salary_xpath).click()
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.tax_xpath).click()
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.report_xpath).click()
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.qualification_xpath).click()
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.membership_xpath).click()
        time.sleep(5)
        print("All tabs are getting displayed")

    def test_personal(self,booting_function):
        self.driver.get(self.url)
        time.sleep(5)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.input_username).send_keys(data.Sahana_Data.username)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.input_password).send_keys(data.Sahana_Data.password)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.login_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.pim_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.user_edit_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.personal_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.nickname_xpath).send_keys(data.Sahana_Data.nickname)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.otherid_xpath).send_keys(data.Sahana_Data.other_id)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.dl_xpath).send_keys(data.Sahana_Data.dl)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.expire_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.expire_xpath).send_keys(data.Sahana_Data.expiry)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.ssn_xpath).send_keys(data.Sahana_Data.ssn)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.sin_xpath).send_keys(data.Sahana_Data.sin)
        time.sleep(10)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.nationality_xpath).click()
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.nationality_xpath).send_keys(data.Sahana_Data.nationality)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.nationality_select).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.marital_xpath).click()
        time.sleep(3)
        # action.move_to_element(self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.marital_select)).click().perform()
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.dob_xpath).send_keys(data.Sahana_Data.dob)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.gender_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.military_xpath).send_keys(data.Sahana_Data.military)
        time.sleep(3)
        # self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.smoker_xpath).click()
        # time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.save_personal).click()
        print("Personal details are saved")


    def test_contact(self,booting_function):
      self.driver.get(self.url)
        time.sleep(5)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.input_username).send_keys(data.Sahana_Data.username)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.input_password).send_keys(data.Sahana_Data.password)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.login_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.pim_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.user_edit_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.contact_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.street1_xpath).send_keys(data.Sahana_Data.Street1)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.street2_xpath).send_keys(data.Sahana_Data.Street2)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.city_xpath).send_keys(data.Sahana_Data.City)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.state_xpath).send_keys(data.Sahana_Data.State)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.pincode_xpath).send_keys(data.Sahana_Data.pincode)
        time.sleep(3)
        wait = WebDriverWait(self.driver,10)
        wait.until(EC.element_to_be_clickable((By.XPATH, data.Sahana_Selectors.country_xpath)))
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.country_xpath).click()
        time.sleep(3)
        wait.until(EC.element_to_be_clickable((By.XPATH, data.Sahana_Selectors.country_dropdown)))
        country_dropdownvalue = self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors().country_dropdown).text
        if country_dropdownvalue.__contains__("Afghanistan"):
            time.sleep(5)
            self.driver.execute_script("var a=arguements[0];a.innerHTML='Afghanistan'",self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors().country_dropdown).click)
            time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.home_xpath).send_keys(data.Sahana_Data.home)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.mobile_xpath).send_keys(data.Sahana_Data.mobile)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.work_xpath).send_keys(data.Sahana_Data.work)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.save_contact).click()
        print("Contact Details are saved")

    def test_emergency(self,booting_function):
        self.driver.get(self.url)
        time.sleep(5)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.input_username).send_keys(data.Sahana_Data.username)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.input_password).send_keys(data.Sahana_Data.password)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.login_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.pim_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.user_edit_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.emergency_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.add_emergency).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.name_emergency).send_keys(data.Sahana_Data.name_emergency)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.relationship).send_keys(data.Sahana_Data.name_emergency)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.home_telephone).send_keys(data.Sahana_Data.home)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.mobile_emergency).send_keys(data.Sahana_Data.mobile)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.save_emergency).click()
        time.sleep(3)
        print("Emergency Contact Created")

    def test_dependancy(self,booting_function):
        self.driver.get(self.url)
        time.sleep(5)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.input_username).send_keys(data.Sahana_Data.username)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.input_password).send_keys(data.Sahana_Data.password)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.login_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.pim_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.user_edit_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.dependants_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.add_emergency).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.name_dependants).send_keys(data.Sahana_Data.firstname)
        time.sleep(3)
        wait = WebDriverWait(self.driver,10)
        wait.until(EC.element_to_be_clickable((By.XPATH, data.Sahana_Selectors.relationship_dependants)))
        value = self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.relationship_dependants)
        value.click()

        wait.until(EC.element_to_be_clickable((By.XPATH, data.Sahana_Selectors.dependant_dropdown)))
        dependant_dropdownvalue = self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors().dependant_dropdown).text
        if dependant_dropdownvalue.__contains__("Child"):
            time.sleep(5)
            self.driver.execute_script("var a=arguements[0];a.innerHTML='Child'",self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors().dependant_dropdown).click)
            time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.dob_dependants).send_keys(data.Sahana_Data.dob)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.save_dependancy).click()
        print("Dependancy Added")

    def test_searchbox_validation(self,booting_function):
        self.driver.get(self.url)
        time.sleep(5)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.input_username).send_keys(data.Sahana_Data.username)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.input_password).send_keys(data.Sahana_Data.password)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.login_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.search_xpath)
        element1 = self.driver.find_element(by=By.LINK_TEXT, value="Admin")
        print(element1.is_displayed())
        time.sleep(3)
        element2 = self.driver.find_element(by=By.LINK_TEXT, value="PIM")
        print(element2.is_displayed())
        time.sleep(3)
        element3 = self.driver.find_element(by=By.LINK_TEXT, value="Leave")
        print(element3.is_displayed())
        time.sleep(3)
        element4 = self.driver.find_element(by=By.LINK_TEXT, value="Time")
        print(element4.is_displayed())
        time.sleep(3)
        element5 = self.driver.find_element(by=By.LINK_TEXT, value="Recruitment")
        print(element5.is_displayed())
        time.sleep(3)
        element6 = self.driver.find_element(by=By.LINK_TEXT, value="My Info")
        print(element6.is_displayed())
        time.sleep(3)
        element7 = self.driver.find_element(by=By.LINK_TEXT, value="Performance")
        print(element7.is_displayed())
        time.sleep(3)
        element8 = self.driver.find_element(by=By.LINK_TEXT, value="Dashboard")
        print(element8.is_displayed())
        time.sleep(3)
        element9 = self.driver.find_element(by=By.LINK_TEXT, value="Directory")
        print(element9.is_displayed())
        time.sleep(3)
        element10 = self.driver.find_element(by=By.LINK_TEXT, value="Maintenance")
        print(element10.is_displayed())
        time.sleep(3)
        element11 = self.driver.find_element(by=By.LINK_TEXT, value="Buzz")
        print(element11.is_displayed())
        time.sleep(3)

    def test_job(self,booting_function):
        self.driver.get(self.url)
        time.sleep(5)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.input_username).send_keys(data.Sahana_Data.username)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.input_password).send_keys(data.Sahana_Data.password)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.login_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.pim_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.user_edit_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.job_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.joined_date_xpath).send_keys(data.Sahana_Data.joined_date)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.job_toggle).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.contract_start).send_keys(data.Sahana_Data.contract_start)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.contract_end).send_keys(data.Sahana_Data.contract_end)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.job_save_xpath).click()
        print("Job details saved successfully")


    
    def test_terminate(self,booting_function):
        self.driver.get(self.url)
        time.sleep(5)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.input_username).send_keys(data.Sahana_Data.username)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.input_password).send_keys(data.Sahana_Data.password)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.login_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.pim_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.user_edit_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.job_xpath).click()
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.terminate_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.terminate_date_xpath).send_keys(data.Sahana_Data.terminate_date)
        time.sleep(3)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.note_job_xpath).send_keys(data.Sahana_Data.note_job)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.terminate_save).click()
        time.sleep(3)
        print("Employee Termination details are saved")

    def test_salary(self,booting_function):
        self.driver.get(self.url)
        time.sleep(5)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.input_username).send_keys(data.Sahana_Data.username)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.input_password).send_keys(data.Sahana_Data.password)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.login_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.pim_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.user_edit_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.salary_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.salary_components_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.salary_components1_xpath).send_keys(data.Sahana_Data.salary_components1)
        time.sleep(3)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.amount_xpath).send_keys(data.Sahana_Data.amount)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.comments_xpath).send_keys(data.Sahana_Data.Comments)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.salary_toggle).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.Acc_no_xpath).send_keys(data.Sahana_Data.Acc_no)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.routing_xpath).send_keys(data.Sahana_Data.routing)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.amount1_xpath).send_keys(data.Sahana_Data.amount1)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.salary_save_xpath).click()
        print("Salary Details added")

    def test_tax(self,booting_function):
        self.driver.get(self.url)
        time.sleep(5)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.input_username).send_keys(data.Sahana_Data.username)
        self.driver.find_element(by=By.NAME, value=data.Sahana_Selectors.input_password).send_keys(data.Sahana_Data.password)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.login_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.pim_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.user_edit_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.tax_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.exemptions_xpath).send_keys(data.Sahana_Data.Exemptions)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=data.Sahana_Selectors.tax_save).click()
        print("Tax Exemptions saved")



